mongo:
  uri: "mongodb://158.69.163.121:42741/"

starting-timer: 15

spawn:
  world: "world"
  x: 0
  y: 100
  z: 0

scoreboard:
  title: "<blue>Mizule <grey>Practice"
  lines:
    - " "
    - "<rainbow>Player: %player%"
    - " "
    - "<rainbow>Online: %online%"
    - " "
    - "store.example.net"

tab:
  header:
    - "hey"
    - "<red>byte"
    - "hey"
  footer:
    - "hey"
    - "<red>byte"
    - "hey"

selector:
  item: "COMPASS"
  enchantments:
    - "DURABILITY:10"
  name: "<red>Server Selector"
  lore:
    - ""
    - "<grey>Right click to go to server"
    - ""
  slot: 1
  amount: 1
kit:
  item: "BOOK"
  enchantments:
    - "DURABILITY:10"
  name: "<red>Kit Selector"
  lore:
    - ""
    - "<grey>Right click to go for kits"
    - ""
  slot: 2
  amount: 1
statistics:
  item: "DIAMOND_SWORD"
  enchantments:
    - "DURABILITY:10"
  name: "<red>Statistics Viewer"
  lore:
    - ""
    - "<grey>Right click to view stats"
    - ""
  slot: 3
  amount: 1

inventory:
  selector:
    title: "<red>Selector Inventory"
    size: 54
    items:
      1:
        item: "DIAMOND_SWORD"
        name: "<red>Test Game"
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test"
          - "<red>test"
          - ""
        amount: 1
        slot: 1
        spawn-world: "world"
        spawn-x: 100
        spawn-y: 100
        spawn-z: 100
  kit:
    title: "<red>Kits Inventory"
    size: 54
    items:
      1:
        item: "BOOK"
        name: "<red>Kit 1"
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test 1"
          - "<red>test 1"
          - ""
        amount: 1
        slot: 1
        editor: 1
      2:
        item: "BOOK"
        name: "<red>Kit 2"
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test 2"
          - "<red>test 2"
          - ""
        amount: 1
        slot: 2
        editor: 2
      3:
        item: "BOOK"
        name: "<red>Kit 3"
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test 3"
          - "<red>test 3"
          - ""
        amount: 1
        slot: 3
        editor: 3
      4:
        item: "null"
        name: "<red>Click to "
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test 1"
          - "<red>test 1"
          - ""
        amount: 1
        slot: 10
        kit: 1
      5:
        item: "null"
        name: "<red>Kit 2"
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test 2"
          - "<red>test 2"
          - ""
        amount: 1
        slot: 11
        kit: 2
      6:
        item: "null"
        name: "<red>Kit 3"
        enchantments:
          - "DURABILITY:10"
        lore:
          - "<red>test 3"
          - "<red>test 3"
          - ""
        amount: 1
        slot: 12
        kit: 3
  statistics:
    title: "<red>Statistics Inventory"
    size: 54
    items:
      1:
        item: "DIAMOND_SWORD"
        name: "<red>Statistics"
        enchantments:
          - "DURABILITY:10"
        lore:
          - ""
          - "<red>Player %player%"
          - "<red>Kills %kills%"
          - "<red>Deaths %deaths%"
          - "<red>Wins %wins%"
          - "<red>Loses %loses%"
          - ""
        amount: 1
        slot: 1

editor:
  inventory:
    title: "<red>Kit Editor"
    size: 54
  hotbar:
    - "0"
    - "1"
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
  hotbar-item: "CYAN_STAINED_GLASS_PANE"
  hotbar-name: "<red>Click to Add"

selection:
  selected-item: "LIME_WOOL"
  unselected-item: "GRAY_WOOL"
  selected-name: "<green>Selected"
  unselected-name: "<red>Not Selected"

sign-format:
  - "%name%"
  - "%kit%"
  - "%arena%"
  - "%players%/%max%"
