license: ""

mongo:
  uri: "mongodb://158.69.163.121:42741/"

selector:
  item: ""
  enchantments:
  name: ""
  lore:
    - ""
    - ""
    - ""
  slot: 1
  amount: 1

sign-format:
  - "%name%"
  - "%kit%"
  - "%arena%"
  - "%queue_player%/%queue_size%"