license: ""

mongo:
  uri: "mongodb://158.69.163.121:42741/"

starting-timer: 15

spawn:
  x: 0
  y: 100
  z: 0

scoreboard:
  title: "<blue>Mizule <grey>Practice"
  lines:
    - " "
    - "<rainbow>Player: %player%"
    - " "
    - "<rainbow>Online: %online%"
    - " "
    - "store.example.net"

tab:
  header:
    - "hey"
    - "<red>byte"
    - "hey"
  footer:
    - "hey"
    - "<red>byte"
    - "hey"

selector:
  item: ""
  enchantments:
  name: ""
  lore:
    - ""
    - ""
    - ""
  slot: 1
  amount: 1

sign-format:
  - "%name%"
  - "%kit%"
  - "%arena%"
  - "%players%/%max%"
