name: zPractice
version: "${pluginVersion}"
main: com.mizuledevelopment.zpractice.zPractice
api-version: "1.18"
website: "${pluginWebsite}"
author: "${pluginAuthor}"
description: "${pluginDescription}"
commands:
  sign:
  arena:
  kit:
